### July 4
GET http://localhost:8000/api/day-for/fireworks/1688428900000 HTTP/1.1

### New Year's Eve
GET http://localhost:8000/api/day-for/fireworks/1672531100000 HTTP/1.1

### New Year Day
GET http://localhost:8000/api/day-for/fireworks/1672617500000 HTTP/1.1

###
GET http://localhost:8000/api/day-for/snow?lat=40.5146926&long=-111.9911154 HTTP/1.1
